[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"
[project]
name = "rice_ml"
version = "0.1.0"
description = "An example Python project"
authors = [{ name = "Randy R. Davila", email = "randyrdavila@gmail.com" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = ["numpy", "matplotlib", "seaborn", "pandas", "requests"]
[project.optional-dependencies]
dev = ["pytest"]
# ---- CRITICAL for src/ layout ----
[tool.setuptools]
package-dir = { "" = "src" }
[tool.setuptools.packages.find]
where = ["src"]
# Pytest config
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]